---
author:
  - 'Ricardo SIGNES <rjbs@cpan.org>'
build_requires:
  Email::Simple::Creator: 2.1
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Email-ARF
no_index:
  directory:
    - inc
    - t
requires:
  Email::MIME: 1.859
  Email::MIME::ContentType: 0
  Email::MIME::Creator: 1.451
  Params::Util: 0
  Scalar::Util: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.004
