author: Ricardo SIGNES <rjbs@cpan.org>
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Email-ARF
no_index: 
  directory: 
    - inc
    - t
requires: 
  Email::MIME: 1.859
  Email::MIME::ContentType: 0
  Params::Util: 0
  Scalar::Util: 0
version: 0.002
